### ISSUE TITLE
404 Not Found Apache Spark .tgz

### ISSUE THREAD

**Issue by tallamjr** [astrolabsoftware/fink-broker#104]
It has become apparent when running CI tests through Travis that a `HTTP/1.1 404 Not Found` was being reported when attempting to pull down `spark-2.4.0-bin-hadoop2.7.tgz` from http://www-us.apache.org/dist/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.7.tgz

As it stands I am getting this error when trying to use the above link:
```
Not Found
The requested URL /dist/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.7.tgz was not found on this server.
```
A working alternative I found is: http://archive.apache.org/dist/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.7.tgz

**Comment by JulienPeloton** [comment]
Thanks @tallamjr! Fixed in #105
