### ISSUE TITLE
Find a logo

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#109]
This is a fun issue - one would need a logo. Any ideas?

**Comment by cAbhi15** [comment]
A logo would be great!! What is the etymology behind the name "Fink" though?

**Comment by tallamjr** [comment]
I see the logo on the README resembles a bird, is this directly linked to the
[fink](https://en.wikipedia.org/wiki/Fink_(software)) project which apparently comes from:
>  The Fink project was started in December 2000 by German hacker Christoph
    Pfisterer. The name Fink is German for finch and is a reference to the name of
    the macOS core, Darwin; Charles Darwin's study of diversity among finches led
    him eventually to the concept of natural selection.

Would you like to stick with the same theme of a finch bird or would alternative
themes be preferred?

I have used a handy website in the past: https://hatchful.shopify.com which can
produce free logos.

**Comment by JulienPeloton** [comment]
Thanks @cAbhi15 and @tallamjr! The idea behind Fink was originally fink as _sneak or informer_ (which is sort of what a broker is!). The ancient form for the bird (_finch_ which is still used in German indeed) helped me to design the first (ugly) visual.

Thanks @tallamjr for the website, I'm actually playing with all possible combinations :D
Feel free to pick up some of your favourite (w/ or w/o the bird) and share them here, and we shall take a decision at some point.

**Comment by JulienPeloton** [comment]
![logo_transparent](https://user-images.githubusercontent.com/20426972/55830075-8033e600-5b10-11e9-8a36-591e21889020.png)

**Comment by JulienPeloton** [comment]
![twitter_header_photo_1](https://user-images.githubusercontent.com/20426972/55832632-41a12a00-5b16-11e9-9e18-dbe7be36b8bd.png)

**Comment by JulienPeloton** [comment]
![facebook_cover_photo_2](https://user-images.githubusercontent.com/20426972/55832657-52ea3680-5b16-11e9-8c26-a6df6c700d42.png)

**Comment by cAbhi15** [comment]
is this any good :P 
![fink logo](https://user-images.githubusercontent.com/19184284/58016376-177e5700-7b1b-11e9-83a1-0c8752ed5e88.png)

**Comment by JulienPeloton** [comment]
Done in #361
