### ISSUE TITLE
Potential update to gitignore required

### ISSUE THREAD

**Issue by tallamjr** [astrolabsoftware/fink-broker#110]
Not sure if this is even an _issue_ but when one runs `fink_test` locally, the following is created:
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        archive/
        web/data/
```
Perhaps one would like to not track these, or are these folders/files useful?

**Comment by JulienPeloton** [comment]
Thanks @tallamjr, these folders do not need to be tracked!

`${FINK_HOME}/web/data` is created the first time `fink` is launched, and `${FINK_HOME}/archive` (or actually whatever folder is specified under `FINK_ALERT_PATH`) is created first when calling `fink start archive`.
