### ISSUE TITLE
Unable to run CI tests in forked repo

### ISSUE THREAD

**Issue by tallamjr** [astrolabsoftware/fink-broker#113]
Due to this line:
```
export FINK_HOME="/home/travis/build/astrolabsoftware/fink-broker"
```
Travis requires the the software to be downloaded expects to run tests against `fink` that resides in the above folder. This is troublesome for forked repos where one wants to tests potential PR code where the actual repo will reside in `$TRAVIS_REPO_SLUG`, for example: 
```
$ git clone --depth=50 --branch=pr/issue/110/gitignore https://github.com/tallamjr/fink-broker.git tallamjr/fink-broker
```

This results in the following error if one attempts to run the CI tests:
```
fink start simulator -c ${FINK_HOME}/conf/fink.conf.travis
No command 'fink' found, did you mean:
 Command 'link' from package 'coreutils' (main)
 Command 'dink' from package 'freedink-engine' (universe)
 Command 'find' from package 'findutils' (main)
 Command 'ink' from package 'ink' (universe)
fink: command not found
The command "fink start simulator -c ${FINK_HOME}/conf/fink.conf.travis" exited with 127.
```

Perhaps it would be best to link to the cloned repo like so:
```
export FINK_HOME="/home/travis/build/${TRAVIS_REPO_SLUG}"
```

https://github.com/tallamjr/fink-broker/issues/1#issue-431434249

**Comment by JulienPeloton** [comment]
Good point, thanks! Actually it is a good practice to use environment variable instead of hardcoded paths (not only for forks!).
