### ISSUE TITLE
update gitignore

### ISSUE THREAD

**Issue by cAbhi15** [astrolabsoftware/fink-broker#135]
**Describe the issue**
in addition to ignoring the folders mentioned in #110 coverage files which are named like .coverage* must also be ignored

**Action item**
simply changing .coverage to .coverage* in the file .gitignore will fix the issue

**Actual behaviour**
Files such as these were being tracked
.coverage.user.number.number

**Comment by JulienPeloton** [comment]
Thanks @cAbhi15, good catch!

**Comment by JulienPeloton** [comment]
Fixed in #136
