### ISSUE TITLE
CI tests fail if the ZTF public website is down

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#151]
**Describe the issue**
If the server hosting the data is down (https://ztf.uw.edu/alerts/public/), the CI tests cannot run. As we do not control the server, this means we are completely stuck until it goes back.

For testing purposes, we have to find an alternative:
- Using git lfs (still an external deps, but with very high uptime)
- Including some files in the repo (tests currently need only 10 alerts).

At first, I would choose the 2nd option which has the advantage to not include a new external dependency.

**Comment by ChristianArnault** [comment]
+1 for second option (since we expect it to be temporary!)

**Comment by JulienPeloton** [comment]
Fixed in #152, #154 and #155
