### ISSUE TITLE
Add Redistribution module

### ISSUE THREAD

**Issue by cAbhi15** [astrolabsoftware/fink-broker#170]
**Describe the issue**
The Kafka based alert distribution module is to be put in place

**Action items**
The following components are to be added:

1. A science database (HBase) reader
    - ability to read some/ all columns corresponding to a row key
    - some filtering on the basis of values in a particular column 

2. An alert Producer
    - use the reader to query the science db
    - produce alerts on topics after serilazing

3. Kafka cluster setup
    - installation script for travis
    - server/ zookeeper configuration files

4. Kafka consumer(s) to verify the redistribution

**Comment by JulienPeloton** [comment]
Implemented in #182
