### ISSUE TITLE
Bump version: 0.2.0

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#175]
**Describe the issue**
The codebase evolved a lot, and some functionalities change/have been removed. A new version is needed.

Action item: make a new release.

**Comment by tallamjr** [comment]
Hi @JulienPeloton , would I be able to help with this one, I'm keen to learn how
to make a release and perhaps I can incorporate this along with #21 ?

For another project I have an open PR regarding dynamic versioning using
`setuptools_scm` to do automatic version bumps but then for releases one creates
`git tag v0.1.2` say. Would this be of interest for this project/something you
would like?

REF:

- https://github.com/LSSTDESC/snmachine/pull/160
- https://github.com/LSSTDESC/snmachine/pull/160#issuecomment-499282045

**Comment by JulienPeloton** [comment]
Hi @tallamjr , thanks for proposing help in this matter! Actually, bumping version involves rather minimalist work for the moment and I keep it for myself. For reference, the steps for a release are:
- update version under `python/fink_broker/__init__.py`
- update version under `fink-broker/build.sbt`
- release the Scala module under `libs/` (compiling latest sources)
- release the python module using `git tag <new_version> / git push origin --tags`
- update the release notes on GH & the website (tracking PRs and issues since the last version).

Having said that, once a few modifications pending and the `setup.py` pushed (there are on a local branch), I would be happy if you can include a dynamic versioning as you propose, and look at #21. The difficulty there however would be to include correctly all the non-python files (`conf/`, `bin/`, `docker/`, `libs/`, `schemas/`) such that users can invoke `fink` by just using `pip/conda install fink-broker`. I'm not sure this would be easy, but it is worth trying.

**Comment by JulienPeloton** [comment]
Actually, the changes in the repo break the previous API (0.1.1), hence the new version will be 0.2.0. Title of the issue changed accordingly.

**Comment by tallamjr** [comment]
> Hi @tallamjr , thanks for proposing help in this matter! Actually, bumping version involves rather minimalist work for the moment and I keep it for myself. For reference, the steps for a release are:
> 
> * update version under `python/fink_broker/__init__.py`
> * update version under `fink-broker/build.sbt`
> * release the Scala module under `libs/` (compiling latest sources)
> * release the python module using `git tag <new_version> / git push origin --tags`
> * update the release notes on GH & the website (tracking PRs and issues since the last version).
> 
> Having said that, once a few modifications pending and the `setup.py` pushed (there are on a local branch), I would be happy if you can include a dynamic versioning as you propose, and look at #21. The difficulty there however would be to include correctly all the non-python files (`conf/`, `bin/`, `docker/`, `libs/`, `schemas/`) such that users can invoke `fink` by just using `pip/conda install fink-broker`. I'm not sure this would be easy, but it is worth trying.

Sounds good. I will give that a go and look in that in due course 👍

**Comment by JulienPeloton** [comment]
Version 0.2.0 released (#192)!

@tallamjr, you can go ahead with dynamic versioning and #21 whenever you have time. Thanks!
