### ISSUE TITLE
Schema for Science DB

### ISSUE THREAD

**Issue by cAbhi15** [astrolabsoftware/fink-broker#180]
**Describe the issue**
The alerts received have a nested [schema](https://zwickytransientfacility.github.io/ztf-avro-alert/schema.html). This schema is preserved while storing alert data in the raw database and is flattened before storing them in the science database.
Currently the science database has a row-key and one column family with several columns.

This issue is for discussion on the most appropriate schema for the science DB. This will change over time with different/increasing use cases.

For an example if the schema of the original alert is preserved and a column family is added for cross-matched tags the schema will look like:
<table>
    <thead>
      <tr>
        <th colspan="1">Row-key(say, candid)</th>
        <th colspan="3">Candidate</th>
        <th colspan="2">cutoutScience</th>
        <th colspan="1">...</th>
        <th colspan="2">prv_candidates</th>
        <th colspan="2">cross-match</th>
      </tr>
      <tr>
        <th>...</th>
        <th>jid</th>
        <th>ra</th>
        <th>...</th>
        <th>fiileName</th>
        <th>stampdata</th>
        <th>...</th>
        <th>candid</th>
        <th>...</th>
        <th>simbadType</th>
        <th>others</th>
      </tr>
    </thead>
  </table>

**Comment by JulienPeloton** [comment]
#347, #351, #355, etc.. and https://github.com/astrolabsoftware/fink-science-portal
