### ISSUE TITLE
Streaming service for alert distribution

### ISSUE THREAD

**Issue by cAbhi15** [astrolabsoftware/fink-broker#193]
**Describe the issue**
The current alert distribution system #182 uses a Spark batch process to read the Science DB and publish alerts to the Kafka Cluster.
However, such a system can not be used to send out alerts in real time as soon as they are received from upstream (and updated in the science db).

**To do**
- Create a streaming service that publishes alerts as soon as they are written to the science DB (HBase). This can be done using an [hbase-connector](https://github.com/apache/hbase-connectors)
- Modify the consumer to receive and decode the alerts

**Comment by JulienPeloton** [comment]
Fixed in #201
