### ISSUE TITLE
Filtering alerts before distribution

### ISSUE THREAD

**Issue by cAbhi15** [astrolabsoftware/fink-broker#203]
**Describe the issue**
In the current distribution system, all of the alerts stored in Science DB are redirected as Kafka messages.
There should be a filtering mechanism before the distribution. The alerts can be filtered on the basis of
- columns of interest
- or some criterion (say, `someParam > someThreshold`)

**To Do**
- Add a filtering mechanism before the distribution of alerts

**Comment by JulienPeloton** [comment]
XML-based filtering done in #206 - python-based filtering (leveltwo) will come in another PR.
