### ISSUE TITLE
raw2science: add generic filtering capability

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#205]
**Describe the issue**
Currently, the `raw2science` service uses hard-coded filters. The idea would be to make this part as much generic as possible, such that the user can upload filters on-demand.

**Comment by cAbhi15** [comment]
@JulienPeloton I am working on using generic filters in form of xml files for alert distribution #203 
I think it would be straight forward to extend it to use here as well.

**Comment by JulienPeloton** [comment]
Xml files? Could you elaborate more on this, and how you want to proceed?

For this task, I had in mind that the user would define his/her own filtering functions in a python module, and them they would be uploaded into fink automatically.

**Comment by cAbhi15** [comment]
@JulienPeloton Give me a minute, I will create a review PR with the work till now.

**Comment by cAbhi15** [comment]
@JulienPeloton Could you please have a look into the PR #206 
The idea is, if one wants to apply relatively simple filters i.e. select some columns, drop some columns or simple criteria such as `some_column >  some_value`, this can be achieved via a simple xml rule file.

**Comment by JulienPeloton** [comment]
Implemented in #209
