### ISSUE TITLE
pip or conda release

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#21]
That would be great to distribute the library via standard channels (pip and/or conda).

**Comment by tallamjr** [comment]
Hi @JulienPeloton , just to confirm; is the idea with this issue to have something like so:

`pip install fink` and `conda install fink`

i.e. to have it easily installable?

(I was meant to be at the DESC Broker workshop but had to pull out last minute, however I am still quite interested in this project)

**Comment by JulienPeloton** [comment]
Hi @tallamjr, yes this is exactly it! 

The code is still very messy as I am building the ground & infrastructure, so most of the issues are reminders for the future to keep focusing on the low level development :-) 
If you are interested in it, I should start to release some beta version for tests in a few weeks from now. I can keep you posted?

**Comment by tallamjr** [comment]
Great, thanks!

I'll make sure to keep an eye out for updates 👍

**Comment by JulienPeloton** [comment]
Actually - I do not plan to release the broker on pip anymore as it is not made for: it is becoming more a framework than a single library. 

The way to install and use the broker is explained here: https://fink-broker.readthedocs.io/en/latest/broker/introduction/ (the cluster configuration is missing though).
