### ISSUE TITLE
Alert Re-distribution: Authentication and Authorization

### ISSUE THREAD

**Issue by cAbhi15** [astrolabsoftware/fink-broker#224]
**Describe the issue**
The current Kafka Cluster for Alert distribution does not utilize any security measure.

**To dos**
The Alert Re-distribution service consists of 3 parts: 
1. Kafka Cluster
2. Producer (Fink)
3. Consumer (science community)

The following is a rough overview of the things to be added to each part of the service:
 1. **Kafka Cluster**
    - Authentication of Producer and Consumer's client app 
    - Authorization of Producer and Consumers against write/read access
    - Managing consumers's apps
2. **Producer**
   - Producing on secured Kafka Cluster
3. **Consumer**
    - Ability to consume from secured Kafka Cluster
    - Some minimal operations on the received stream

**Comment by JulienPeloton** [comment]
Done in #231
