### ISSUE TITLE
Bug: Name for column containing xmatch results changed.

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#234]
**Describe the issue**
The DataFrame column that contains xmatch results has been renamed `cross_match_alerts_per_batch` instead of `simbadType` in PR #209, but the redistribution module still uses the old name (e.g. in `conf/distribution-rules.xml`)

Action item: replace `simbadType` by `cross_match_alerts_per_batch`.

**Comment by cAbhi15** [comment]
Thanks @JulienPeloton 
I will fix it.

**Comment by cAbhi15** [comment]
Fixed in #231 (side effect) see commit 8609d7e

**Comment by cAbhi15** [comment]
@JulienPeloton can we close this issue?

**Comment by JulienPeloton** [comment]
Yes, thanks!
