### ISSUE TITLE
group_df_into_struct: problem if two final entries have the same name

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#235]
**Describe the issue**
If we have a df with the following schema:
```
root
 |-- objectId: string (nullable = true)
 |-- candid: long (nullable = true)
 |-- candidate_ra: double (nullable = true)
 |-- candidate_dec: double (nullable = true)
 |-- candidate_candid: long (nullable = true)
```
and we want to group all `candidate_*` into a struct like:
```
root
 |-- objectId: string (nullable = true)
 |-- candid: long (nullable = true)
 |-- candidate: struct (nullable = false)
 |    |-- ra: double (nullable = true)
 |    |-- dec: double (nullable = true)
 |    |-- candid: long (nullable = true)
```

using `distributionutils.group_df_into_struct`, it will not work. The problem is that both `flat_cols` and `cols_to_group` will have a final column named `candid`.

**Comment by cAbhi15** [comment]
Thanks @JulienPeloton for pointing this out.
This needs to fixed.

**Comment by JulienPeloton** [comment]
Thanks @cAbhi15. Can you take care of it?

**Comment by cAbhi15** [comment]
Sure! I will try to fix it.

**Comment by JulienPeloton** [comment]
Thanks :-)

**Comment by cAbhi15** [comment]
Fixed in #231 (side effect) see commit f481a5e

**Comment by cAbhi15** [comment]
@JulienPeloton can we close this issue?

**Comment by JulienPeloton** [comment]
Yes! Thanks.
