### ISSUE TITLE
Topic name in distribute should be an input

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#236]
**Describe the issue**

```python
# in bin/distribute.py
# Publish Kafka topic(s)
# Ensure that the topic(s) exist on the Kafka Server)
df_kafka\
    .write\
    .format("kafka")\
    .option("kafka.bootstrap.servers", "localhost:9093")\
    .option("topic", "fink_outstream")\
    .save()
```

The topic name used for redistribution should not be hardcoded in `bin/distribute.py` but instead an argument user can specify.

Action item: add an entry in the configuration file for the redistribution topic name.

**Comment by cAbhi15** [comment]
Fixed in #231 (side effect)

**Comment by cAbhi15** [comment]
@JulienPeloton can we close this issue?

**Comment by JulienPeloton** [comment]
Yes, thanks!
