### ISSUE TITLE
Integration with Slack

### ISSUE THREAD

**Issue by cAbhi15** [astrolabsoftware/fink-broker#248]
**Describe the issue**
Integration with Slack can be helpful in many ways. This issue is for discussion on the features' list that can be included in Fink-Slack integration. 
The idea is to have a module (say, `fink_broker.slackUtils` ) with APIs for the required features.

The basics would be to have an API for:
- sending messages to channels on the slack workspace
- sending messages to individual users on the slack workspace

Please feel free to comment with more features to add to the Fink-Slack integration

**Comment by JulienPeloton** [comment]
Done in #249
