### ISSUE TITLE
Updating gitignore

### ISSUE THREAD

**Issue by tallamjr** [astrolabsoftware/fink-broker#274]
**Describe the issue**
    

After running `python setup.py install` of the `fink-broker` the following
surplus files are created.

These perhaps do not need to be tracked so I would propose to add these to the
gitignore file.

        Untracked files:
          (use "git add <file>..." to include in what will be committed)
                build/
                dist/
                fink_broker.egg-info/

            modified:   .gitignore

**System Information:**

 - Operating System: [`macOS-10.14.16`]:
 - Fink Version: [`0.2.1`]
 - Occurred on which branch and with what commit: [`master-a02fe9b`]

**Comment by JulienPeloton** [comment]
Thanks @tallamjr for pointing out this, these can be indeed ignored. 

However you probably noticed the `setup.py` (in its current form) is not really useful to install the software as it just package the python files without all the rest. I think fink-client would be more appropriate for a pip release than the broker itself.

**Comment by tallamjr** [comment]
> Thanks @tallamjr for pointing out this, these can be indeed ignored.
> 
> However you probably noticed the `setup.py` (in its current form) is not really useful to install the software as it just package the python files without all the rest. I think fink-client would be more appropriate for a pip release than the broker itself.

Ah, that is very true. Perhaps all the additions are overkill, this could probably be closed off then 👍

**Comment by JulienPeloton** [comment]
No I would still include them if the change are ready as the role of the `setup.py` might evolve in the future (this way we would have the gitignore ready).

**Comment by tallamjr** [comment]
Closed with #275
