### ISSUE TITLE
fink_kafka: list ACL

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#280]
**Describe the issue**
There is no way to quickly inspect authentication and authorisation on Kafka.

Action item: implement a new option in `fink_kafka`, called `--list-acl`, that wraps `${KAFKA_HOME}/bin/kafka-acls.sh --authorizer kafka.security.auth.SimpleAclAuthorizer --authorizer-properties zookeeper.connect=localhost:2182 --list`

**Comment by cAbhi15** [comment]
Thanks @JulienPeloton for raising this issue. 
Sorry for having missed such a trivial functionality :disappointed:

**Comment by JulienPeloton** [comment]
Thanks for the quick fix @cAbhi15 in #282 .
