### ISSUE TITLE
Mismatch between distribution_schema and distribution-rules

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#289]
**Describe the issue**

#### Distribution rules

`conf/distribution_rules.xml` defines which fields should be included in the outgoing alert. Currently it contains:

```xml
<!-- columns to select for distribution -->
<select>
   <column name="objectId"/>
   <column name="candid"/>
   <column name="candidate"/>
   <column name="cutoutTemplate"/>
   <column name="cutoutScience"/>
   <column name="cutoutDifference"/>
   <column name="prv_candidates"/>
   <column name="cross_match_alerts_per_batch"/>
   <column name="status"/>
 </select>
```

#### Distribution schema
`schemas/distribution_schema.avsc` contains the schema (JSON) that is used to decode the alert on the client side. It should contain all fields that were defined by the distribution rules, and only those (no extra!). Currently, we have:

```json
{
   "type": "record",
   "name": "topLevelRecord",
   "fields": [
     {
       "name": "objectId",
       "type": [
         "string",
         "null"
       ]
     },
     {
       "name": "schemavsn",
       "type": [
         "string",
         "null"
       ]
     },
     {
       "name": "publisher",
       "type": [
         "string",
         "null"
       ]
     },
     {
       "name": "candid",
       "type": [
         "long",
         "null"
       ]
     },
     {
       "name": "timestamp",
       "type": [
         "string",
         "null"
       ]
     },
     {
       "name": "cross_match_alerts_per_batch",
       "type": [
         "string",
         "null"
       ]
     },
...
```
were I cut for brevity. 

#### The mismatch

By comparing the two, we find that the schema contains more fields than what is declared in the distribution rules (see e.g. `schemavsn`, `timestamp`, ...). This will typically lead to decoding error on the client side (see https://github.com/astrolabsoftware/fink-client/issues/26).

Action item:
- Short term: fix the distribution rules to match the current distribution schema (the latter is more complete than the former)
- Medium term: The schema for outgoing alerts should ideally be the schema for incoming alerts (fixed) plus the schema for added values (can vary over time). This way, we would just care about defining added value schema, and all the rest would be just copied from incoming alerts.

**Comment by JulienPeloton** [comment]
Note that the second item will be carried out in #290

**Comment by cAbhi15** [comment]
Thanks @JulienPeloton for finding the problem here.
If I understand correctly, the issue [fink-client/#26](https://github.com/astrolabsoftware/fink-client/issues/26) is due to the mismatch in schema of output stream and the schema used for decoding the alerts?
Does skipping the use of `distribution_rules.xml` (see #232 ) fixes the problem?

**Comment by JulienPeloton** [comment]
Hi @cAbhi15 

> If I understand correctly, the issue [fink-client/#26](https://github.com/astrolabsoftware/fink-client/issues/26) is due to the mismatch in schema of output stream and the schema used for decoding the alerts?

yes correct. 

> Does skipping the use of `distribution_rules.xml` (see #232 ) fixes the problem?

It does, in the sense that the schema of the outgoing schema of the alert would correspond to the schema stored on the server - but in that case all alerts (i.e. no filtering) would be transmitted to the client if no python filters are active.

To minimize manual intervention in the future, I will redesign the way schemas are handled to make sure we introduce only atomic changes (only appending new fields to incoming schema instead of specifying manually all fields).

**Comment by cAbhi15** [comment]
> To minimize manual intervention in the future, I will redesign the way schemas are handled to make sure we introduce only atomic changes (only appending new fields to incoming schema instead of specifying manually all fields).

Got it ! Thanks!
