### ISSUE TITLE
Dockerfile for the fink_alert_simulator

### ISSUE THREAD

**Issue by ChrisArnault** [astrolabsoftware/fink-broker#322]
**Pip is not available in the docker image created for fink**
_When building the docker image for fink, we expect the user invoking it, to complete it by some "pip install …" actions, but pip itself is not available by default_

**Suggested**
_Add "apt-get install python3-pip" at the end of the Dockerfile, (or to the tutorial)_

CA

**Comment by JulienPeloton** [comment]
Hum, that's strange because pip should be installed as part of anaconda3 (it is even used inside the Dockefile -- see line 67). I can see it installed:

```bash
07:30:31 mac-peloton:fink-broker julien$ docker run --rm --tty --interactive \
>   -v $FINK_HOME:/home/fink-broker \
>   -v $FINK_SCIENCE:/home/fink-science \
>   -v $FINK_FILTERS:/home/fink-filters \
>   -v /var/run/docker.sock:/var/run/docker.sock \
>   --net host \
>   fink-broker bash
root@docker-desktop:/home/fink-broker# which pip
/home/libs/anaconda3/miniconda/bin/pip
```
Are you sure your build was successful?

**Comment by JulienPeloton** [comment]
Likely an issue with Docker for Windows.
