### ISSUE TITLE
kubernetes support

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#368]
**Describe the issue**
we are investigating the deployment of Fink using Kubernetes. Action item:
- [x] build the image
- [x] integrate with [kind](https://github.com/kubernetes-sigs/kind) for the tests
- [x] add deployment scripts + configuration files.

**Comment by JulienPeloton** [comment]
Deployment scripts available at https://github.com/astrolabsoftware/fink-k8s

We still need to update the `fink` binary with k8s configuration.

**Comment by fjammes** [comment]
Kubernetes support has been improved.
