### ISSUE TITLE
Build fink-broker image from fink-broker repository

### ISSUE THREAD

**Issue by fjammes** [astrolabsoftware/fink-broker#661]
- Check if miniconda is required
- Add CI to fink-broker to build and push image
- Add k8s ci to fink-broker

**Comment by fjammes** [comment]
Hi @JulienPeloton , two questions on my side:
1. Is the file `fink-broker/Dockerfile` still useful?
2. Would it be possible to use python from spark-py image instead of miniconda?

**Comment by JulienPeloton** [comment]
Hi @fjammes 
1. No, it is deprecated.
2. For compatibility reasons, I prefer miniconda. We use the conda environment in production, so if we use the python of the system in the test suite, we would not be able to check dependencies properly.
3. oh yes... I need to check, but this can be removed this week.

**Comment by fjammes** [comment]
@JulienPeloton 
FYI, I have created an annotated tag "2.7.1" on master branch tip, so that the version is now: 
```fjammes@host ~/src/fink-broker: git describe --dirty --always 
2.7.1-2-gce0ab6a
```
Command for annotated tag is:
```
git tag 2.7.1 -m "Release 2.7.1"
```

**Comment by fjammes** [comment]
Hi @JulienPeloton , FYI I have these errors messages while building image:

**Comment by JulienPeloton** [comment]
Hi @fjammes -- you can safely ignore these errors for the moment.
