### ISSUE TITLE
[k8s] split code dependencies

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#685]
The dependencies are currently all entangled in the code -- while ideally the different services should be isolated:

| service | Spark + basic python deps | Science deps | Simulator | Kafka | HBase |
|-----------|-----------------|-------------------|---------------|--------|---------------|
| stream2raw | :heavy_check_mark: | :x: | :heavy_check_mark: | :heavy_check_mark: | :x: |
| raw2science | :heavy_check_mark: | :heavy_check_mark: | :x: | :x: | :x: |
| distribute | :heavy_check_mark: | :x: | :x: | :heavy_check_mark: | :x: |
| science_archival | :heavy_check_mark: | :x: | :x: | :x: | :heavy_check_mark: |
| index_archival | :heavy_check_mark: | :x: | :x: | :x: | :heavy_check_mark: |

To do:
- [ ] Isolate different services
- [x] release new `requirements.txt` for different purposes

**Comment by fjammes** [comment]
Closing issue which is has been solve in https://github.com/astrolabsoftware/fink-broker/issues/698
