### ISSUE TITLE
[Hostless Detection] Update thresholds in the Telegram bot

### ISSUE THREAD

**Issue by utthishtastro** [astrolabsoftware/fink-broker#892]
@JulienPeloton We would like to introduce thresholds and report candidates that pass them in the Telegram bot.
Report candidates` if (science_score <= 0.5 and template_score <= 0.85) `
Let me know if you have any further questions. Thank you

**Comment by JulienPeloton** [comment]
Hello @utthishtastro -- thanks. I transfered this request in this repo as the filtering code lives here.

**Comment by utthishtastro** [comment]
> Hello @utthishtastro -- thanks. I transfered this request in this repo as the filtering code lives here.

Thank you
